[package]
name = "trueos-picasso-example"
version = "0.1.0"
edition = "2024"
publish = false

[package.metadata.trueos-blueprint]
replicatable = true

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(target_os, values("trueos"))'] }

[lib]
path = "src/lib.rs"

[[bin]]
name = "trueos-picasso-example"
path = "src/main.rs"
test = false
bench = false

[dependencies]
libm = "0.2"
trueos = { path = "../TRUEOS-Blueprints/api" }
trueos-picasso = { path = "../TRUEOS-Picasso", default-features = false }

[build-dependencies]
gltf = { version = "1.4.1", default-features = false, features = ["utils"] }
